import Link from "next/link";

export default function TermsPage() {
        return (
                <div className="bg-neutral-50 py-12">
                        <div className="mx-auto max-w-5xl space-y-10 px-4 sm:px-6 lg:px-8 text-gray-700">
                                <header className="space-y-4 text-center sm:text-left">
                                        <p className="text-sm font-semibold uppercase tracking-wide text-amber-600">
                                                Terms &amp; Conditions
                                        </p>
                                        <h1 className="text-3xl font-bold text-gray-900 sm:text-4xl">
                                                Terms &amp; Conditions (Terms of Use)
                                        </h1>
                                        <p className="text-base text-gray-600">Effective date: 01 September 2025</p>
                                        <p>
                                                These Terms govern your access to and use of Industrial Print Solutions
                                                websites, pages, and services ("Platform") and any purchase of products or
                                                services offered by Industrial Print Solutions ("IPS", "we", "us",
                                                "our"). By accessing or using the Platform, you agree to be bound by these
                                                Terms and the policies referenced here (Privacy Policy, Cancellation &amp;
                                                Refund Policy, Shipping &amp; Delivery Policy, and Disclaimer).
                                        </p>
                                        <p>
                                                This document is an electronic record under the Information Technology
                                                Act, 2000 and applicable rules; it is generated by a computer system and
                                                does not require any physical or digital signatures. It is published in
                                                accordance with Rule 3(1) of the Information Technology (Intermediary
                                                Guidelines) Rules to make our rules/policies available for your use of the
                                                Platform.
                                        </p>
                                </header>

                                <div className="space-y-8">
                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">1) About these Terms</h2>
                                                <p>
                                                        These Terms govern your access to and use of the Platform and any
                                                        purchase of products or services offered by IPS. By accessing or
                                                        using the Platform, you agree to be bound by these Terms and the
                                                        policies referenced here, including our
                                                        {" "}
                                                        <span className="font-semibold">Privacy Policy</span>,
                                                        {" "}
                                                        <span className="font-semibold">Cancellation &amp; Refund Policy</span>,
                                                        {" "}
                                                        <span className="font-semibold">Shipping &amp; Delivery Policy</span>, and
                                                        <span className="font-semibold"> Disclaimer</span>.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">2) Eligibility &amp; account</h2>
                                                <p>
                                                        You confirm that you are competent to contract under Indian law and,
                                                        where you act for a company, that you are authorized to bind it. You
                                                        must keep your account credentials secure and are responsible for all
                                                        activities under your account.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">
                                                        3) Ordering flow (custom &amp; standard products)
                                                </h2>
                                                <ul className="list-disc space-y-2 pl-6">
                                                        <li>
                                                                <span className="font-semibold">Product selection &amp; artwork intake.</span>
                                                                {" "}
                                                                For customized items, you upload or share your logo/artwork and instructions.
                                                        </li>
                                                        <li>
                                                                <span className="font-semibold">Proof &amp; approval.</span>
                                                                {" "}
                                                                We share a digital proof; production begins only after your
                                                                approval. Minor colour variation may occur between screen and print.
                                                        </li>
                                                        <li>
                                                                <span className="font-semibold">Print-on-demand.</span>
                                                                {" "}
                                                                Customized jobs are made specifically for you and are generally non-returnable except for manufacturing defects or transit damage (see Cancellation &amp; Refund).
                                                        </li>
                                                        <li>
                                                                <span className="font-semibold">Pricing &amp; taxes.</span>
                                                                {" "}
                                                                Prices are in INR and exclusive of GST unless stated. Taxes (if
                                                                applicable) are shown at checkout, and shipping is free on every
                                                                order.
                                                        </li>
                                                        <li>
                                                                <span className="font-semibold">Payment.</span>
                                                                {" "}
                                                                Payments are processed by trusted payment gateways; we don’t store full card details. If a third-party payment/financing page is used, their terms and privacy policy apply.
                                                        </li>
                                                </ul>
                                        </section>

                                        <section className="space-y-4">
                                                <h2 className="text-xl font-semibold text-gray-900">
                                                        4) Customer logos &amp; IPS content — ownership and licences
                                                </h2>
                                                <div className="space-y-3">
                                                        <h3 className="text-lg font-semibold text-gray-900">Your Logo/Artwork</h3>
                                                        <ul className="space-y-2 pl-6 text-gray-700 list-disc">
                                                                <li>
                                                                        <span className="font-semibold">Ownership.</span>
                                                                        {" "}
                                                                        You (or your licensors) retain all rights in your logo/artwork.
                                                                </li>
                                                                <li>
                                                                        <span className="font-semibold">Limited licence to IPS.</span>
                                                                        {" "}
                                                                        You grant IPS a limited, revocable, non-exclusive, royalty-free licence to use your logo/artwork solely to design previews, personalize, print, pack, deliver, and (where applicable) host related QR training pages for your orders/subscriptions.
                                                                </li>
                                                                <li>
                                                                        <span className="font-semibold">No cross-use or marketing.</span>
                                                                        {" "}
                                                                        We will not use your logo/artwork for other customers, portfolios, ads, listings, or social media without your explicit written consent.
                                                                </li>
                                                                <li>
                                                                        <span className="font-semibold">Your warranties.</span>
                                                                        {" "}
                                                                        You warrant that you have all rights to submit and authorise our use of the logo/artwork and that the content is lawful, non-infringing, and non-misleading. You agree to indemnify IPS against third-party claims arising from your assets.
                                                                </li>
                                                        </ul>
                                                </div>
                                                <div className="space-y-3">
                                                        <h3 className="text-lg font-semibold text-gray-900">IPS Content</h3>
                                                        <p>
                                                                Designs, illustrations, templates, layouts, copy, product photography, and the Platform’s look-and-feel are owned by or licensed to IPS. You receive a non-exclusive licence to use the final printed outputs at your sites; no right to reproduce IPS templates or site content unless we permit in writing. This mirrors standard “use of content” terms seen on similar sites.
                                                        </p>
                                                </div>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">
                                                        5) Acceptable use &amp; security rules
                                                </h2>
                                                <p>
                                                        You agree not to: (a) access data not intended for you; (b) probe, scan, or test vulnerabilities; (c) interfere with services (e.g., virus, flooding, crashing); (d) send unsolicited commercial emails via the Platform; or (e) upload unlawful, defamatory, obscene, or infringing content. Breaches may attract civil/criminal liability and cooperation with law enforcement.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">
                                                        6) Third-party links &amp; services
                                                </h2>
                                                <p>
                                                        The Platform may link to third-party websites/services (payment pages, courier tracking, cloud previews). Their terms and privacy policies apply; IPS is not responsible for their practices or content.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">
                                                        7) Shipping &amp; delivery (summary)
                                                </h2>
                                                <p>
                                                        Lead times and carriers are described in our Shipping &amp; Delivery Policy (design proof → production → dispatch timelines; tracking; packaging; delivery windows). In case of high order volumes or force-majeure events, dispatch can be delayed with notice.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">
                                                        8) Cancellation &amp; refund (summary)
                                                </h2>
                                                <p>
                                                        Customized items: free cancellation until proof approval (or within a short time window stated in the policy). After approval/production start: no cancellation; defects/transit damage claims must be raised within the stated window with photos/unboxing video; remedy is reprint/replacement (refunds only if reprint is impossible).
                                                </p>
                                                <p>
                                                        Standard items: returns allowed as per policy if unused and in original packaging. Industry examples commonly specify time limits, evidence, and refund windows. Full details are in our Cancellation &amp; Refund Policy, which forms part of these Terms.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">9) Warranties &amp; disclaimers</h2>
                                                <p>
                                                        Products and site content are provided “as is/available”. IPS disclaims all implied warranties (merchantability, fitness, non-infringement) to the maximum extent permitted by law.
                                                </p>
                                                <p>
                                                        Safety posters/signage are educational/awareness tools and do not replace statutory training, audits, or legal compliance obligations applicable to your workplace.
                                                </p>
                                                <p>
                                                        We do not guarantee uninterrupted or error-free operation; availability may be affected by factors beyond our control. Similar disclaimers are standard across industry.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">
                                                        10) Limitation of liability
                                                </h2>
                                                <p>
                                                        To the fullest extent permitted by law, IPS shall not be liable for any indirect, incidental, special, consequential, exemplary or punitive damages, including lost profits/revenues/data, arising from or related to your use of the Platform or products. In all cases, IPS’s aggregate liability shall not exceed the amounts actually paid by you for the product/service giving rise to the claim (or any lower statutory cap, if applicable). Comparable formulations appear in common Indian e-commerce templates.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">11) Indemnity</h2>
                                                <p>
                                                        You agree to indemnify and hold harmless IPS, its officers, directors, employees and agents from any claims, liabilities, damages, costs and expenses (including reasonable attorneys’ fees) arising out of: (a) your breach of these Terms or policies; (b) your infringement of third-party rights (including logo/artwork you supplied); or (c) your violation of law.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">
                                                        12) Pricing, promotions &amp; errors
                                                </h2>
                                                <p>
                                                        We reserve the right to modify pricing, offers, or product specifications at any time. In case of typographical errors or incorrect pricing, we may cancel orders or request confirmation at the correct price before processing.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">
                                                        13) Intellectual property claims (notice)
                                                </h2>
                                                <p>
                                                        If you believe any material on the Platform infringes your IP, email
                                                        <Link
                                                                href="mailto:info@industrialprintsolutions.com"
                                                                className="text-amber-600 underline underline-offset-4"
                                                        >
                                                                info@industrialprintsolutions.com
                                                        </Link>
                                                        {" "}
                                                        with: (i) your contact details; (ii) a description and proof of rights; (iii) URL/location of the allegedly infringing material; and (iv) a good-faith statement and requested action.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">
                                                        14) Electronic communications &amp; consent
                                                </h2>
                                                <p>
                                                        By using the Platform or sharing your contact details, you consent to receive service communications (order status, design approvals, dispatch, invoices). Marketing communications, if any, will follow our Privacy Policy and can be opted out.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">15) Privacy</h2>
                                                <p>
                                                        Our Privacy Policy explains what data we collect, how we use/share it, security, retention, and your rights (including grievance redressal). Please read it carefully; it is incorporated into these Terms by reference.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">16) Force majeure</h2>
                                                <p>
                                                        Neither party is liable for delay/failure caused by events beyond reasonable control (e.g., natural disasters, acts of government, strikes, network outages, pandemics).
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">
                                                        17) Suspension/termination
                                                </h2>
                                                <p>
                                                        We may suspend/terminate access or cancel orders (with refund, where applicable) if we suspect fraud, misuse, security risks, rights violations, or breach of these Terms.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">
                                                        18) Governing law &amp; jurisdiction
                                                </h2>
                                                <p>
                                                        These Terms are governed by laws of India. Subject to applicable law, courts at Kanpur, Uttar Pradesh shall have exclusive jurisdiction over disputes arising from or in connection with the Platform or these Terms.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">19) Changes to Terms</h2>
                                                <p>
                                                        We may update these Terms from time to time. Continued use of the Platform after changes indicates your acceptance; please review this page periodically.
                                                </p>
                                        </section>

                                        <section className="space-y-3">
                                                <h2 className="text-xl font-semibold text-gray-900">
                                                        20) Contact &amp; grievance redressal
                                                </h2>
                                                <p>
                                                        <span className="font-semibold">Grievance Officer – Mr. Shubham</span>
                                                </p>
                                                <p>
                                                        Email:
                                                        {" "}
                                                        <Link
                                                                href="mailto:info@industrialprintsolutions.com"
                                                                className="text-amber-600 underline underline-offset-4"
                                                        >
                                                                info@industrialprintsolutions.com
                                                        </Link>
                                                </p>
                                                <p>Mobile: +91 9936814137</p>
                                                <p>Address: 127/196, U-Block, Niralanagar, Kanpur, 208014</p>
                                        </section>
                                </div>
                        </div>
                </div>
        );
}
